// Code generated by endpoints_gen.go; DO NOT EDIT.

package aws

// Known regions.
const (
	APNortheast1 = "ap-northeast-1" // Asia Pacific (Tokyo)
	APNortheast2 = "ap-northeast-2" // Asia Pacific (Seoul)
	APSouth1     = "ap-south-1"     // Asia Pacific (Mumbai)
	APSoutheast1 = "ap-southeast-1" // Asia Pacific (Singapore)
	APSoutheast2 = "ap-southeast-2" // Asia Pacific (Sydney)
	CACentral1   = "ca-central-1"   // Canada (Central)
	EUCentral1   = "eu-central-1"   // EU (Frankfurt)
	EUWest1      = "eu-west-1"      // EU (Ireland)
	EUWest2      = "eu-west-2"      // EU (London)
	EUWest3      = "eu-west-3"      // EU (Paris)
	SAEast1      = "sa-east-1"      // South America (Sao Paulo)
	USEast1      = "us-east-1"      // US East (N. Virginia)
	USEast2      = "us-east-2"      // US East (Ohio)
	USWest1      = "us-west-1"      // US West (N. California)
	USWest2      = "us-west-2"      // US West (Oregon)
	CNNorth1     = "cn-north-1"     // China (Beijing)
	CNNorthwest1 = "cn-northwest-1" // China (Ningxia)
	USGovWest1   = "us-gov-west-1"  // AWS GovCloud (US)
)

var knownRegions = []string{
	APNortheast1,
	APNortheast2,
	APSouth1,
	APSoutheast1,
	APSoutheast2,
	CACentral1,
	EUCentral1,
	EUWest1,
	EUWest2,
	EUWest3,
	SAEast1,
	USEast1,
	USEast2,
	USWest1,
	USWest2,
	CNNorth1,
	CNNorthwest1,
	USGovWest1,
	"external-1",
}
